remote_theme: "mmistakes/minimal-mistakes@4.27.3"
minimal_mistakes_skin: "air"
title: Hertz Identity
description: Haiying Zeng
kramdown:
  input: GFM
  syntax_highlighter: rouge
plugins:
- jekyll-include-cache
